services:
  nginx:
    image: nginx
    container_name: yii2-it-nginx
    ports:
      - "8090:80"
    volumes:
      - .:/var/www
      - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  php:
    env_file:
      - .env
    container_name: yii2-it-php
    build:
      context: .
      dockerfile: .docker/php/Dockerfile
    volumes:
      - .:/var/www
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - db

  db:
    env_file:
      - .env
    container_name: yii2-it-db
    image: percona:8
    restart: always
    ports:
      - "127.0.0.1:13306:3306"